user:
  name_max: 50
  email_max: 250
  password_min: 6
  user_show: 15
avatar:
  size: 35
  size_home: 50
newspost:
  number: 15
  content_size: 300
  picture_size: 5
picture:
  picture_size: 600
seed:
  take: 10
  content: 10
comment:
  comment_max_size: 150
